export const SCORING_VERSION = "rules-v1.7-2026-09-29";

export const SCORING_WEIGHTS = {
  technical: 35,
  experience: 25,
  seniority: 15,
  language: 10,
  location: 10,
  other: 5,
} as const;

export const CANDIDATE_PROFILE = {
  // Confirmed range; use the upper bound only to identify explicit requirements above it.
  supportExperienceMaxYears: 6,
  postgresExperience: "SQL/RLS; advanced database internals unverified",
  // Confirmed by the candidate: no hands-on use of these tools or product security work.
  confirmedNoExperience: ["AWS", "Terraform", "Kubernetes", "product security"],
  targetRoleTerms: [
    "full stack",
    "full-stack",
    "backend",
    "frontend",
    "software developer",
    "software engineer",
    "web developer",
    "integration",
    "implementation",
    "systems analyst",
    "system analyst",
    "business analyst",
    "application support",
    "technical support",
    "support engineer",
    "infrastructure",
    "system administrator",
    "systems administrator",
    "technical operations",
    "automation",
    "solutions engineer",
    "technical consultant",
  ],
  strongSkills: [
    "javascript",
    "typescript",
    "react",
    "node",
    "node.js",
    "express",
    "php",
    "mysql",
    "postgresql",
    "postgres",
    "sql",
    "supabase",
    "svelte",
    "api",
    "apis",
    "rest",
    "git",
    "github",
    "vercel",
    "suitecrm",
    "crm",
  ],
  transferableSkills: [
    "integration",
    "implementation",
    "troubleshooting",
    "technical support",
    "application support",
    "help desk",
    "infrastructure",
    "network",
    "networking",
    "server",
    "servers",
    "windows",
    "linux",
    "incident",
    "business analysis",
    "business analyst",
    "systems",
    "saas",
    "cloud",
    "automation",
  ],
  axisTerms: {
    development: [
      "developer",
      "software engineer",
      "full stack",
      "full-stack",
      "backend",
      "frontend",
      "react",
      "node",
      "javascript",
      "typescript",
      "php",
      "svelte",
    ],
    integrations: [
      "integration",
      "integrations",
      "implementation",
      "api",
      "apis",
      "rest",
      "crm",
      "automation",
      "solutions engineer",
    ],
    technicalFunctional: [
      "business analyst",
      "systems analyst",
      "system analyst",
      "functional analyst",
      "technical analyst",
      "requirements",
      "process",
      "stakeholder",
      "implementation",
    ],
    infrastructureSupport: [
      "technical support",
      "application support",
      "support engineer",
      "infrastructure",
      "system administrator",
      "systems administrator",
      "sysadmin",
      "network",
      "server",
      "incident",
      "troubleshooting",
      "technical operations",
      "sre",
      "site reliability",
    ],
  },
} as const;
